import { StaticText } from '../../i18n/AutoTranslate.jsx'
const statuses = ['Neu', 'Aktualisiert', 'Prüfung erforderlich', 'Unverändert', 'Fehlerhaft']

export default function ImportPreparation({ sourceOptions = null }) {
  return <div className="import-preparation">
    {sourceOptions && <section className="import-preparation__section" aria-labelledby="import-source-heading"><div className="import-preparation__heading"><h2 id="import-source-heading"><StaticText source={"1. Bereich auswählen"} /></h2><p><StaticText source={"Wähle den vorgesehenen Stammdatenbereich für den späteren CSV-Import."} /></p></div><div className="import-source-options">{sourceOptions.map(({ label, description }) => <div className="import-source-option" key={label}><strong>{label}</strong><span>{description}</span></div>)}</div></section>}
    <section className="import-preparation__section" aria-labelledby="import-file-heading"><div className="import-preparation__heading"><h2 id="import-file-heading">{sourceOptions ? '2' : '1'}<StaticText source={". CSV-Datei auswählen"} /></h2><p><StaticText source={"Die Dateiauswahl ist vorbereitet; die CSV-Verarbeitung wird in einem späteren Schritt ergänzt."} /></p></div><label className="import-dropzone"><input type="file" accept=".csv,text/csv" disabled /><strong><StaticText source={"CSV-Datei auswählen"} /></strong><span><StaticText source={"Upload und Verarbeitung sind noch nicht aktiviert."} /></span></label></section>
    <section className="import-preparation__section" aria-labelledby="import-preview-heading"><div className="import-preparation__heading"><h2 id="import-preview-heading">{sourceOptions ? '3' : '2'}<StaticText source={". Vorschau & Validierung"} /></h2><p><StaticText source={"Nach der späteren Verarbeitung erscheinen hier geprüfte Zeilen und erkannte Änderungen."} /></p></div><div className="import-empty-state"><StaticText source={"Noch keine CSV-Datei zur Vorschau ausgewählt."} /></div></section>
    <section className="import-preparation__section" aria-labelledby="import-status-heading"><div className="import-preparation__heading"><h2 id="import-status-heading"><StaticText source={"Statusliste"} /></h2><p><StaticText source={"Diese Status werden für jede Importzeile bereitgestellt."} /></p></div><div className="import-status-list">{statuses.map((status) => <span className="import-status" key={status}>{status}</span>)}</div></section>
    <section className="import-preparation__section import-preparation__section--muted" aria-labelledby="import-confirm-heading"><div className="import-preparation__heading"><h2 id="import-confirm-heading"><StaticText source={"Fehlerliste & bewusste Übernahme"} /></h2><p><StaticText source={"Fehlerliste und Übernahme werden erst aktiviert, wenn die CSV-Logik, Validierung und Datenübernahme umgesetzt sind."} /></p></div><div className="import-confirmation"><span><StaticText source={"Keine Übernahme möglich, solange keine CSV-Logik vorhanden ist."} /></span><button className="button" type="button" disabled><StaticText source={"Änderungen übernehmen"} /></button></div></section>
  </div>
}
