import { StaticText, TranslatedProps } from '../../i18n/AutoTranslate.jsx'
import { useEffect, useState } from 'react'
import { createEmptyInkassoDeadline, inkassoDeadlinePresentation } from '../../lib/inkasso.js'
import { deadlineDateTimeLabel, shortReminderRecipient } from '../../lib/caseDeadline.js'
import { EditIcon } from '../icons.jsx'

function formatDate(value) { return value ? new Intl.DateTimeFormat('de-DE').format(new Date(`${value}T12:00:00`)) : '—' }
function formatTimestamp(value) { const date = value?.toDate?.(); return date ? new Intl.DateTimeFormat('de-DE', { dateStyle: 'medium', timeStyle: 'short' }).format(date) : '—' }
function deadlineClass(deadline) { const kind = inkassoDeadlinePresentation(deadline).kind; return kind === 'overdue' ? 'damage-deadlines__date damage-deadlines__date--overdue' : kind === 'today' ? 'damage-deadlines__date damage-deadlines__date--today' : kind === 'urgent' ? 'damage-deadlines__date damage-deadlines__date--urgent' : kind === 'warning' ? 'damage-deadlines__date damage-deadlines__date--warning' : 'damage-deadlines__date' }

function DeadlineModal({ canEdit, deadline, mode, onClose, onDelete, onSave }) {
  const [editing, setEditing] = useState(mode === 'new')
  const [values, setValues] = useState(() => ({ date: deadline?.date || createEmptyInkassoDeadline().date, time: deadline?.time || '', reminderEnabled: Boolean(deadline?.reminderEnabled), note: deadline?.note || '' }))
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')

  useEffect(() => { function closeOnEscape(event) { if (event.key === 'Escape' && !saving) onClose() } window.addEventListener('keydown', closeOnEscape); return () => window.removeEventListener('keydown', closeOnEscape) }, [onClose, saving])
  const update = (field, value) => { setValues((current) => ({ ...current, [field]: value })); setError('') }
  async function submit(event) { event.preventDefault(); setSaving(true); setError(''); try { await onSave(mode === 'new' ? null : deadline, values); onClose() } catch (saveError) { setError(saveError.message || 'Der Termin konnte nicht gespeichert werden.') } finally { setSaving(false) } }
  async function remove() { if (!deadline || !window.confirm('Termin wirklich löschen?')) return; setSaving(true); setError(''); try { await onDelete(deadline); onClose() } catch (deleteError) { setError(deleteError.message || 'Der Termin konnte nicht gelöscht werden.') } finally { setSaving(false) } }
  const title = mode === 'new' ? 'Termin hinzufügen' : editing ? 'Termin bearbeiten' : 'Termindetails'

  return <div className="todo-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !saving) onClose() }}><section className="todo-quick-edit-modal damage-deadline-modal" role="dialog" aria-modal="true" aria-labelledby="inkasso-deadline-modal-title"><form className="todo-quick-editor" onSubmit={submit} noValidate>
    <div className="todo-quick-editor__heading damage-deadline-modal__heading"><h2 id="inkasso-deadline-modal-title">{title}</h2>{canEdit && mode !== 'new' && !editing && <TranslatedProps sources={{"title":"Termin bearbeiten","aria-label":"Termin bearbeiten"}}><button className="todo-detail-section-edit" type="button" onClick={() => { setValues({ date: deadline.date, time: deadline.time || '', reminderEnabled: Boolean(deadline.reminderEnabled), note: deadline.note || '' }); setEditing(true) }} title="Termin bearbeiten" aria-label="Termin bearbeiten"><EditIcon size={14} /></button></TranslatedProps>}</div>
    {editing ? <div className="todo-quick-editor__grid damage-deadline-modal__fields"><label className="form-field"><span><StaticText source={"Datum *"} /></span><input autoFocus type="date" value={values.date} required onChange={(event) => update('date', event.target.value)} /></label><label className="form-field"><span><StaticText source={"Uhrzeit"} /></span><input type="time" value={values.time} onChange={(event) => update('time', event.target.value)} /></label><label className="form-field"><span><StaticText source={"Erinnerung"} /></span><select value={values.reminderEnabled ? 'on' : 'off'} onChange={(event) => update('reminderEnabled', event.target.value === 'on')}><option value="off"><StaticText source={"Aus"} /></option><option value="on"><StaticText source={"An"} /></option></select></label><label className="form-field damage-deadline-modal__note"><span><StaticText source={"Bemerkung"} /></span><textarea rows="5" value={values.note} maxLength="4000" onChange={(event) => update('note', event.target.value)} /></label></div> : <div className="damage-deadline-modal__details"><section><h3><StaticText source={"Termininformationen"} /></h3><dl><div><dt><StaticText source={"Datum / Uhrzeit"} /></dt><dd><span className={deadlineClass(deadline)}>{inkassoDeadlinePresentation(deadline).label} · {deadlineDateTimeLabel(deadline.date, deadline.time)}</span></dd></div><div><dt><StaticText source={"Erinnerung"} /></dt><dd><span className={deadline.reminderEnabled ? 'damage-deadlines__reminder damage-deadlines__reminder--on' : 'damage-deadlines__reminder'}>{<StaticText source={deadline.reminderEnabled ? 'An' : 'Aus'} />}</span></dd></div><div><dt><StaticText source={"Empfänger"} /></dt><dd>{shortReminderRecipient(deadline)}</dd></div><div><dt><StaticText source={"Bemerkung"} /></dt><dd className="damage-deadline-modal__note-value">{deadline.note || '—'}</dd></div></dl></section><section><h3><StaticText source={"Systeminformationen"} /></h3><dl><div><dt><StaticText source={"Erstellt von"} /></dt><dd>{deadline.createdByName || '—'}</dd></div><div><dt><StaticText source={"Erstellt am"} /></dt><dd>{formatTimestamp(deadline.createdAt)}</dd></div><div><dt><StaticText source={"Zuletzt aktualisiert von"} /></dt><dd>{deadline.updatedByName || '—'}</dd></div><div><dt><StaticText source={"Zuletzt aktualisiert am"} /></dt><dd>{formatTimestamp(deadline.updatedAt)}</dd></div></dl></section></div>}
    {error && <p className="form-error">{<StaticText source={error} />}</p>}<div className="form-actions">{canEdit && mode !== 'new' && <button className="button button--danger" type="button" disabled={saving} onClick={remove}><StaticText source={"Löschen"} /></button>}{editing ? <><button className="button button--secondary" type="button" disabled={saving} onClick={mode === 'new' ? onClose : () => setEditing(false)}><StaticText source={"Abbrechen"} /></button><button className="button" type="submit" disabled={saving}>{<StaticText source={saving ? 'Wird gespeichert …' : 'Speichern'} />}</button></> : <button className="button button--secondary" type="button" onClick={onClose}><StaticText source={"Schließen"} /></button>}</div>
  </form></section></div>
}

export default function InkassoDeadlinesCard({ canEdit, deadlines, loading, onDelete, onSave }) {
  const [modal, setModal] = useState(null)
  return <section className="todo-detail-content damage-deadlines" aria-labelledby="inkasso-deadlines-title">{modal && <DeadlineModal canEdit={canEdit} deadline={modal.deadline} mode={modal.mode === 'new' ? 'new' : 'details'} onClose={() => setModal(null)} onDelete={onDelete} onSave={onSave} />}<div className="todo-detail-section-heading"><h3 id="inkasso-deadlines-title"><StaticText source={"Termine & Fristen"} /></h3>{canEdit && <button className="button damage-deadlines__add" type="button" onClick={() => setModal({ mode: 'new', deadline: null })}><StaticText source={"Termin hinzufügen"} /></button>}</div><div className="todos-table-frame damage-deadlines__table-frame"><table className="data-table todos-table damage-deadlines__table"><thead><tr><th><StaticText source={"Datum / Uhrzeit"} /></th><th><StaticText source={"Erinnerung"} /></th><th><StaticText source={"An"} /></th><th><StaticText source={"Bemerkung"} /></th></tr></thead><tbody>{loading ? <tr><td className="table-state" colSpan="4"><StaticText source={"Termine werden geladen …"} /></td></tr> : !deadlines.length ? <tr><td className="table-state inkasso-empty-state" colSpan="4"><StaticText source={"Noch keine Termine oder Fristen hinterlegt."} /></td></tr> : deadlines.map((deadline) => <tr key={deadline.id} className="damage-deadlines__row" tabIndex="0" role="button" onClick={() => setModal({ mode: 'details', deadline })} onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); setModal({ mode: 'details', deadline }) } }} aria-label={`Termin vom ${formatDate(deadline.date)} öffnen`}><td><span className={deadlineClass(deadline)}>{inkassoDeadlinePresentation(deadline).label} · {deadlineDateTimeLabel(deadline.date, deadline.time)}</span></td><td><span className={deadline.reminderEnabled ? 'damage-deadlines__reminder damage-deadlines__reminder--on' : 'damage-deadlines__reminder'}>{<StaticText source={deadline.reminderEnabled ? 'An' : 'Aus'} />}</span></td><td className="damage-deadlines__recipient" title={deadline.reminderRecipientEmail || ''}>{shortReminderRecipient(deadline)}</td><td className="damage-deadlines__note" title={deadline.note || ''}>{deadline.note || '—'}</td></tr>)}</tbody></table></div></section>
}
