import { MODULES, PERMISSION_LEVELS, ROLE_LABELS, USER_ROLES, normalizePermissions } from '../../lib/permissions.js'

const fields = [['firstName', 'Vorname'], ['lastName', 'Nachname'], ['email', 'E-Mail'], ['department', 'Abteilung'], ['jobTitle', 'Funktion'], ['phone', 'Telefon / Durchwahl'], ['personnelNumber', 'Personalnummer'], ['employmentStart', 'Eintrittsdatum']]

export default function UserManagementForm({ value, isNew, canManagePermissions, saving, onChange, onCancel, onSubmit }) {
  const permissions = normalizePermissions(value.permissions)
  const set = (field, next) => onChange({ ...value, [field]: next })
  const setPermission = (module, next) => set('permissions', { ...permissions, [module]: next })
  return <section className="admin-user-form"><div className="admin-user-form__heading"><div><h2>{isNew ? 'Mitarbeiter anlegen' : 'Mitarbeiter verwalten'}</h2><p>{isNew ? 'Neue Konten werden standardmäßig als User angelegt.' : 'Stammdaten und Zugriff kompakt verwalten.'}</p></div><button type="button" className="button button--secondary" onClick={onCancel}>Schließen</button></div><form onSubmit={onSubmit}><div className="admin-user-form__grid">{fields.map(([field, label]) => <label className="form-field" key={field}><span>{label}</span><input type={field === 'email' ? 'email' : field === 'employmentStart' ? 'date' : 'text'} required={['firstName', 'lastName', 'email'].includes(field)} value={value[field] ?? ''} onChange={(event) => set(field, event.target.value)} /></label>)}{isNew && <label className="form-field"><span>Initiales Passwort</span><input type="password" minLength="8" required value={value.password ?? ''} onChange={(event) => set('password', event.target.value)} /></label>}<label className="form-field"><span>Status</span><select value={value.active === false ? 'inactive' : 'active'} onChange={(event) => set('active', event.target.value === 'active')}><option value="active">Aktiv</option><option value="inactive">Deaktiviert</option></select></label><label className="form-field"><span>Rolle</span>{canManagePermissions ? <select value={value.role ?? 'user'} onChange={(event) => set('role', event.target.value)}>{USER_ROLES.map((role) => <option key={role} value={role}>{ROLE_LABELS[role]}</option>)}</select> : <input value={ROLE_LABELS[value.role] || 'User'} readOnly />}</label></div>{canManagePermissions && <fieldset className="admin-permissions"><legend>Berechtigungen</legend><div className="admin-permissions__list">{Object.entries(MODULES).map(([module, { label }]) => <label key={module}><span>{label}</span><select value={permissions[module]} onChange={(event) => setPermission(module, event.target.value)}>{PERMISSION_LEVELS.map((level) => <option key={level} value={level}>{level === 'none' ? 'Kein Zugriff' : level === 'view' ? 'Nur ansehen' : 'Bearbeiten'}</option>)}</select></label>)}</div></fieldset>}<div className="admin-user-form__actions"><button className="button" type="submit" disabled={saving}>{saving ? 'Wird gespeichert …' : isNew ? 'Mitarbeiter anlegen' : 'Änderungen speichern'}</button></div></form></section>
}
