import { createPortal } from 'react-dom'
import { CloseIcon } from '../icons.jsx'

function timestamp(value) { const date = value?.toDate?.() || (value ? new Date(value) : null); return date && !Number.isNaN(date.getTime()) ? new Intl.DateTimeFormat('de-DE', { dateStyle: 'short', timeStyle: 'short' }).format(date) : '—' }
function percentage(value) { return Number.isFinite(value) ? `${value}%` : '—' }
function colorLabel(value) { return { green: 'Im Plan', yellow: 'Beobachten', red: 'Kritisch', grey: 'Prognose abgelaufen' }[value] || 'Keine Prognose' }
function Range({ forecast }) { if (!forecast?.arrivals) return null; const earliest = new Date(forecast.arrivals.optimistic).getTime(); const latest = new Date(forecast.arrivals.pessimistic).getTime(); const deadline = new Date(forecast.deadlineAt).getTime(); const min = Math.min(earliest, deadline); const max = Math.max(latest, deadline); const place = (value) => `${Math.max(0, Math.min(100, ((value - min) / Math.max(1, max - min)) * 100))}%`; return <div className="shipment-tracking-forecast-modal__ranges"><div><span>Entladefenster · spätestens</span><div className="shipment-tracking-forecast-modal__axis"><i style={{ left: place(deadline) }} /></div><small>{timestamp(forecast.deadlineAt)}</small></div><div><span>Optimistisch bis pessimistisch</span><div className="shipment-tracking-forecast-modal__axis shipment-tracking-forecast-modal__axis--forecast"><i style={{ left: place(earliest), width: `${Math.max(2, ((latest - earliest) / Math.max(1, max - min)) * 100)}%` }} /></div><small>{timestamp(forecast.arrivals.optimistic)} – {timestamp(forecast.arrivals.pessimistic)}</small></div></div> }
function historyLabel(item) { return `${timestamp(item.createdAt)} · ${colorLabel(item.state)} · ${percentage(item.onTimeSharePercent)}${item.thresholds ? ` · rot bis ${item.thresholds.red}% / grün ab ${item.thresholds.green}%` : ''}` }
export default function ShipmentTrackingForecastModal({ data, loading, error, refreshing, onRefresh, onClose }) {
  const forecast = data?.forecast
  return createPortal(<div className="shipment-tracking-editor-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !refreshing) onClose() }}><section className="shipment-tracking-editor shipment-tracking-forecast-modal" role="dialog" aria-modal="true" aria-labelledby="shipment-tracking-forecast-title"><div className="shipment-tracking-editor__heading"><div><h2 id="shipment-tracking-forecast-title">Transportprognose</h2><p>{forecast ? colorLabel(forecast.state) : 'Wird geladen …'}</p></div><button type="button" onClick={onClose} aria-label="Dialog schließen" disabled={refreshing}><CloseIcon /></button></div>{loading && <p>Prognose wird geladen …</p>}{error && <p className="form-error">{error}</p>}{forecast?.kind === 'none' && <p>{forecast.message}</p>}{forecast?.kind === 'arrival' && <div className={`shipment-tracking-forecast-modal__arrival shipment-tracking-forecast-modal__arrival--${forecast.state}`}><strong>{forecast.state === 'green' ? 'Angekommen innerhalb des Entladefensters' : 'Angekommen nach Ende des Entladefensters'}</strong><span>{timestamp(forecast.actualArrivalUnloadingAt)}</span></div>}{forecast?.kind === 'forecast' && <div className="shipment-tracking-forecast-modal__content"><div className={`shipment-tracking-forecast-modal__status shipment-tracking-forecast-modal__status--${forecast.state}`}><strong>{colorLabel(forecast.state)}</strong><span>Anteil der Prognosespanne bis zum Slotende: {percentage(forecast.onTimeSharePercent)}</span></div><Range forecast={forecast} /><dl><div><dt>Optimistisch</dt><dd>{timestamp(forecast.arrivals.optimistic)}</dd></div><div><dt>Realistisch</dt><dd>{timestamp(forecast.arrivals.realistic)}</dd></div><div><dt>Grundlage</dt><dd>{forecast.source === 'actual_departure_loading' ? 'Tatsächliche Abfahrt Ladestelle' : forecast.source === 'actual_arrival_loading' ? 'Tatsächliche Ankunft Ladestelle' : 'Voraussichtliche Ankunft Ladestelle'}</dd></div><div><dt>Gültig bis</dt><dd>{forecast.expiresAt ? timestamp(forecast.expiresAt) : 'Bis zur tatsächlichen Entladeankunft'}</dd></div><div><dt>Farbgrenzen</dt><dd>Rot bis {forecast.thresholds.red}% · Grün ab {forecast.thresholds.green}%</dd></div></dl><section><h3>Annahmen und Faktoren</h3><ul>{forecast.assumptions.map((item) => <li key={item}>{item}</li>)}</ul></section>{data?.history?.length > 0 && <details><summary>Prognosehistorie ({data.history.length})</summary><ol>{data.history.map((item) => <li key={item.id}>{historyLabel(item)}</li>)}</ol></details>}</div>}<div className="shipment-tracking-editor__actions"><button className="button button--secondary" type="button" onClick={onClose} disabled={refreshing}>Schließen</button>{onRefresh && <button className="button" type="button" onClick={onRefresh} disabled={refreshing}>{refreshing ? 'Aktualisiert …' : 'Aktualisieren'}</button>}</div></section></div>, document.body)
}
