import { StaticText, TranslatedProps } from '../../i18n/AutoTranslate.jsx'
import { formatPalletNumber } from './palletFormatters.js'
import { PALLET_TYPES } from '../../constants/pallets.js'

export default function PalletMovementForm({ accountLinks = [], carriers, customers, editingMovement, formError, historicalCarrier, historicalCustomer, isSubmitting, modal = false, movementCalculation, movementForm, onCancel, onChange, onDelete, onStationChange, onSubmit, selectedCarrier, selectedCustomer }) {
  const title = editingMovement ? 'Palettenbewegung bearbeiten' : 'Bewegung hinzufügen'
  return <form className={`pallet-entry-form pallet-movement-form${modal ? ' pallet-movement-form--modal' : ''}`} onSubmit={onSubmit}>
    <div className="pallet-entry-form__header">{modal ? <h2 id="pallet-movement-modal-title">{title}</h2> : <h3>{title}</h3>}{modal && <TranslatedProps sources={{"aria-label":"Dialog schließen","title":"Schließen"}}><button className="pallet-movement-modal__close" type="button" onClick={onCancel} disabled={isSubmitting} aria-label="Dialog schließen" title="Schließen">×</button></TranslatedProps>}</div>
    <div className="pallet-movement-reference-grid">
      <label className="form-field"><span><StaticText source={"Transportnummer / unsere Nummer"} /></span><input value={movementForm.tourNumber} onChange={(event) => onChange('tourNumber', event.target.value)} /></label>
      <label className="form-field"><span><StaticText source={"Datum"} /></span><input type="date" value={movementForm.date} onChange={(event) => onChange('date', event.target.value)} /></label>
      <label className="form-field"><span><StaticText source={"Palettenschein-Nr."} /></span><input value={movementForm.palletReceiptNumber} onChange={(event) => onChange('palletReceiptNumber', event.target.value)} /></label>
      <label className="form-field"><span><StaticText source={"Palettenart"} /></span><select value={movementForm.palletType} onChange={(event) => onChange('palletType', event.target.value)}>{PALLET_TYPES.map((type) => <option key={type} value={type}>{type}</option>)}</select></label>
    </div>
    <section className="pallet-movement-partner-grid">
      <label className="form-field pallet-movement-partner"><span><StaticText source={"Kunde"} /></span><select value={movementForm.customerId} onChange={(event) => onChange('customerId', event.target.value)}><option value=""><StaticText source={"Kunde auswählen"} /></option>{historicalCustomer && <option value={historicalCustomer.id}>{<StaticText source={historicalCustomer.label} />}</option>}{customers.map((item) => <option key={item.id} value={item.id}>{item.companyName} · {<StaticText source={item.debtorNumber ? `Debitor ${item.debtorNumber}` : 'ohne Debitorennummer'} />}</option>)}</select></label>
      <output className="pallet-movement-change"><span><StaticText source={"Palettenveränderung"} /></span><strong>{<StaticText source={selectedCustomer ? `${formatPalletNumber(movementCalculation.customerBalance, true)} Paletten` : '0 Paletten'} />}</strong></output>
      <label className="form-field pallet-movement-partner"><span><StaticText source={"Unternehmer"} /></span><select value={movementForm.carrierId} onChange={(event) => onChange('carrierId', event.target.value)}><option value=""><StaticText source={"Unternehmer auswählen"} /></option>{historicalCarrier && <option value={historicalCarrier.id}>{<StaticText source={historicalCarrier.label} />}</option>}{carriers.map((item) => <option key={item.id} value={item.id}>{item.companyName} · {<StaticText source={item.creditorNumber ? `Kreditor ${item.creditorNumber}` : 'ohne Kreditorennummer'} />}</option>)}</select></label>
      <output className="pallet-movement-change"><span><StaticText source={"Palettenveränderung"} /></span><strong>{<StaticText source={selectedCarrier ? `${formatPalletNumber(movementCalculation.carrierBalance, true)} Paletten` : '0 Paletten'} />}</strong></output>
    </section>
    <section className="pallet-movement-matrix">
      <div className="pallet-movement-matrix__grid">
        <span></span><span><StaticText source={"Erhalten"} /></span><span><StaticText source={"Abgegeben"} /></span><span><StaticText source={"Bemerkung"} /></span>
        <strong><StaticText source={"Ladestelle"} /></strong><label><span className="sr-only"><StaticText source={"Ladestelle erhalten"} /></span><TranslatedProps sources={{"aria-label":"Ladestelle erhalten"}}><input aria-label="Ladestelle erhalten" inputMode="numeric" min="0" step="1" type="number" value={movementForm.loadingPoint.received} onChange={(event) => onStationChange('loadingPoint', 'received', event.target.value)} /></TranslatedProps></label><label><span className="sr-only"><StaticText source={"Ladestelle abgegeben"} /></span><TranslatedProps sources={{"aria-label":"Ladestelle abgegeben"}}><input aria-label="Ladestelle abgegeben" inputMode="numeric" min="0" step="1" type="number" value={movementForm.loadingPoint.delivered} onChange={(event) => onStationChange('loadingPoint', 'delivered', event.target.value)} /></TranslatedProps></label><label><span className="sr-only"><StaticText source={"Bemerkung zur Ladestelle"} /></span><TranslatedProps sources={{"aria-label":"Bemerkung zur Ladestelle"}}><input aria-label="Bemerkung zur Ladestelle" value={movementForm.loadingPoint.note} onChange={(event) => onStationChange('loadingPoint', 'note', event.target.value)} /></TranslatedProps></label>
        <strong><StaticText source={"Entladestelle"} /></strong><label><span className="sr-only"><StaticText source={"Entladestelle erhalten"} /></span><TranslatedProps sources={{"aria-label":"Entladestelle erhalten"}}><input aria-label="Entladestelle erhalten" inputMode="numeric" min="0" step="1" type="number" value={movementForm.unloadingPoint.received} onChange={(event) => onStationChange('unloadingPoint', 'received', event.target.value)} /></TranslatedProps></label><label><span className="sr-only"><StaticText source={"Entladestelle abgegeben"} /></span><TranslatedProps sources={{"aria-label":"Entladestelle abgegeben"}}><input aria-label="Entladestelle abgegeben" inputMode="numeric" min="0" step="1" type="number" value={movementForm.unloadingPoint.delivered} onChange={(event) => onStationChange('unloadingPoint', 'delivered', event.target.value)} /></TranslatedProps></label><label><span className="sr-only"><StaticText source={"Bemerkung zur Entladestelle"} /></span><TranslatedProps sources={{"aria-label":"Bemerkung zur Entladestelle"}}><input aria-label="Bemerkung zur Entladestelle" value={movementForm.unloadingPoint.note} onChange={(event) => onStationChange('unloadingPoint', 'note', event.target.value)} /></TranslatedProps></label>
      </div>
    </section>
    {formError && <p className="field-error">{formError}</p>}
    <div className="form-actions">{editingMovement && <button className="button button--danger form-actions__delete" type="button" onClick={onDelete} disabled={isSubmitting}><StaticText source={"Löschen"} /></button>}{accountLinks.map((link) => <button className="button button--secondary" type="button" key={link.partnerId} onClick={link.onClick} disabled={isSubmitting}>{link.label}</button>)}<button className="button button--secondary" type="button" onClick={onCancel} disabled={isSubmitting}><StaticText source={"Verwerfen"} /></button><button className="button" type="submit" disabled={isSubmitting}>{<StaticText source={isSubmitting ? 'Wird gespeichert …' : 'Speichern'} />}</button></div>
  </form>
}
