import { StaticText } from '../i18n/AutoTranslate.jsx'
import { useEffect, useState } from 'react'
import { doc, onSnapshot } from 'firebase/firestore'
import { db } from '../lib/firebase.js'
import { DEFAULT_SHIPMENT_TRACKING_FORECAST_SETTINGS, SHIPMENT_TRACKING_FORECAST_SETTINGS_PATH, normalizeShipmentTrackingForecastSettings } from '../../shared/shipmentTrackingForecastSettings.js'

export default function ShipmentTrackingHelpPage() {
  const [settings, setSettings] = useState(DEFAULT_SHIPMENT_TRACKING_FORECAST_SETTINGS)
  useEffect(() => onSnapshot(doc(db, SHIPMENT_TRACKING_FORECAST_SETTINGS_PATH), (snapshot) => setSettings(normalizeShipmentTrackingForecastSettings(snapshot.exists() ? snapshot.data() : DEFAULT_SHIPMENT_TRACKING_FORECAST_SETTINGS))), [])
  return <main className="shipment-tracking-help-page"><header><h2><StaticText source="Sendungsverfolgung erklärt" /></h2><p>Die Sendungsverfolgung trennt den operativen Fortschritt, feste Handlungsempfehlungen und die Transportprognose bewusst voneinander.</p></header><section><h3>Handlungsempfehlung</h3><p>Die Symbole zeigen höchstens drei konkrete, aktuell offene Themen – kritisch vor Hinweis. Ein Umschlag steht für eine manuell zu prüfende Eingangsmail, KZ für ein fehlendes Kennzeichen und das Stoppschild für eine pausierte Automatik. Der einfache LKW bzw. die Stopuhr folgt nur festen Fristen und fehlenden bestätigbaren Angaben.</p><ul><li>Vor der Ladung zählen Arbeitszeitstunden rückwärts vom frühesten Ladebeginn.</li><li>Nach Ankunft, Beladestart und Beladeende zählen verstrichene Zeitstunden.</li><li>Eine Stopuhr ersetzt während der Beladung den einfachen LKW; beide melden nie denselben offenen Sachverhalt.</li><li>Diese Anzeigen lösen keine neue automatische E-Mail aus.</li></ul><p><strong>Aktuelle Fristen:</strong> ohne Ladeankunft gelb {settings.timing.noArrivalYellowWorkingHours} / rot {settings.timing.noArrivalRedWorkingHours} Arbeitsstunden; mit Lade-ETA gelb {settings.timing.estimatedArrivalYellowWorkingHours} / rot {settings.timing.estimatedArrivalRedWorkingHours} Arbeitsstunden.</p></section><section><h3>Transportprognose</h3><p>Der LKW mit Bewegungslinien ist ausschließlich die Prognose. Sie entsteht automatisch nur bei einer neuen bzw. geänderten voraussichtlichen oder tatsächlichen Ladeankunft sowie bei der tatsächlichen Abfahrt. „Aktualisieren“ im Prognosefenster erstellt bewusst eine neue Berechnung aus allen dann verfügbaren Daten.</p><p>Die Prognose zeigt optimistische, realistische und pessimistische Ankunft. Die Farbe beschreibt den berechneten Anteil dieser Spanne, der spätestens am Entladeende liegt – keine garantierte oder gemessene Pünktlichkeitswahrscheinlichkeit. Fehlende Informationen sind als Annahmen sichtbar. Eine aus tatsächlicher Abfahrt erzeugte Hauptprognose läuft bis zur tatsächlichen Entladeankunft; frühere Grundlagen laufen nach der angenommenen Beladedauer ab und werden grau.</p><p><strong>Aktuelle Farbgrenzen:</strong> rot bis {settings.redThresholdPercent}% · grün ab {settings.greenThresholdPercent}%.</p></section><section><h3>Abschluss</h3><p>Mit der tatsächlichen Ankunft an der Entladestelle endet jede weitere Prognoseberechnung. Das Haus ist grün bei Ankunft bis zum Ende des Entladefensters und gelb bei späterer Ankunft. Die Prognosehistorie bleibt zur Analyse erhalten.</p></section></main>
}
